# YAI service defaults
runtime_user=yai
runtime_group=yai
control_user=yai
control_group=yai
default_shell_entrypoint=/usr/bin/yai
default_control_entrypoint=/usr/bin/yai-ctl
default_interactive_entrypoint=/usr/bin/yai-sh
