#pragma once

#ifndef INCLUDE_SUPERVISOR_SUPERVISOR_EVENT_H
#define INCLUDE_SUPERVISOR_SUPERVISOR_EVENT_H

enum yai_supervisor_event_kind {
    YAI_SUPERVISOR_EVENT_UNKNOWN = 0,
    YAI_SUPERVISOR_EVENT_START,
    YAI_SUPERVISOR_EVENT_STOP,
    YAI_SUPERVISOR_EVENT_MEDIATION,
    YAI_SUPERVISOR_EVENT_REPLAY,
    YAI_SUPERVISOR_EVENT_FAULT
};

#endif
