#pragma once

#ifndef INCLUDE_TRANSPORT_CONTRACT_STATE_H
#define INCLUDE_TRANSPORT_CONTRACT_STATE_H

enum yai_transport_contract_state {
    YAI_TRANSPORT_CONTRACT_UNKNOWN = 0,
    YAI_TRANSPORT_CONTRACT_NEGOTIATING,
    YAI_TRANSPORT_CONTRACT_ACTIVE,
    YAI_TRANSPORT_CONTRACT_DEGRADED,
    YAI_TRANSPORT_CONTRACT_CLOSED
};

#endif
