# Type Path                    Mode UID GID Age Argument
d /run/yai                     0755 yai yai -
d /run/yai/control             0755 yai yai -
d /run/yai/sockets             0755 yai yai -
d /run/yai/locks               0755 yai yai -
d /run/yai/pids                0755 yai yai -
d /run/yai/tmp                 0750 yai yai -

d /var/lib/yai                 0755 yai yai -
d /var/lib/yai/runtime         0755 yai yai -
d /var/lib/yai/graph           0755 yai yai -
d /var/lib/yai/state           0755 yai yai -
d /var/lib/yai/registry        0755 yai yai -
d /var/lib/yai/manifests       0755 yai yai -
d /var/lib/yai/client          0755 yai yai -

d /var/cache/yai               0755 yai yai -
d /var/cache/yai/runtime       0755 yai yai -

d /var/log/yai                 0755 yai yai -
d /var/spool/yai               0755 yai yai -
d /var/spool/yai/outbox        0755 yai yai -
d /var/tmp/yai                 1777 yai yai -
d /tmp/yai                     1777 yai yai -

z /run/yai                     0755 yai yai -
z /run/yai/control             0755 yai yai -
z /run/yai/sockets             0755 yai yai -
z /run/yai/locks               0755 yai yai -
z /run/yai/pids                0755 yai yai -
z /run/yai/tmp                 0750 yai yai -
