#pragma once

#ifndef INCLUDE_NET_TOPOLOGY_STATE_H
#define INCLUDE_NET_TOPOLOGY_STATE_H

enum yai_net_topology_state {
    YAI_NET_TOPOLOGY_UNKNOWN = 0,
    YAI_NET_TOPOLOGY_DISCOVERING,
    YAI_NET_TOPOLOGY_STABLE,
    YAI_NET_TOPOLOGY_DEGRADED,
    YAI_NET_TOPOLOGY_PARTITIONED
};

#endif
