#pragma once

#ifndef INCLUDE_IPC_SESSION_STATE_H
#define INCLUDE_IPC_SESSION_STATE_H

enum yai_ipc_session_state {
    YAI_IPC_SESSION_UNKNOWN = 0,
    YAI_IPC_SESSION_OPEN,
    YAI_IPC_SESSION_NEGOTIATING,
    YAI_IPC_SESSION_READY,
    YAI_IPC_SESSION_CLOSED,
    YAI_IPC_SESSION_FAILED
};

#endif
