#pragma once

#ifndef INCLUDE_TRACE_RECORD_TYPES_H
#define INCLUDE_TRACE_RECORD_TYPES_H

enum yai_trace_record_kind {
    YAI_TRACE_RECORD_UNKNOWN = 0,
    YAI_TRACE_RECORD_EVENT,
    YAI_TRACE_RECORD_DECISION,
    YAI_TRACE_RECORD_AUDIT,
    YAI_TRACE_RECORD_METRIC
};

#endif
