#pragma once

#ifndef INCLUDE_TRACE_SESSION_STATE_H
#define INCLUDE_TRACE_SESSION_STATE_H

enum yai_trace_session_state {
    YAI_TRACE_SESSION_UNKNOWN = 0,
    YAI_TRACE_SESSION_OPEN,
    YAI_TRACE_SESSION_FLUSHING,
    YAI_TRACE_SESSION_CLOSED
};

#endif
