#pragma once

#ifndef INCLUDE_TRACE_STATUS_H
#define INCLUDE_TRACE_STATUS_H

enum yai_trace_status {
    YAI_TRACE_STATUS_UNKNOWN = 0,
    YAI_TRACE_STATUS_INIT,
    YAI_TRACE_STATUS_READY,
    YAI_TRACE_STATUS_DRAINING,
    YAI_TRACE_STATUS_FAILED
};

#endif
